//
//  DnDBModifiers.h
//  TheeEndThee
//
//  Created by Martin-Gilles Lavoie on 2020-11-15.
//  Copyright © 2020 DoRyu. All rights reserved.
//

#import "DoJSONBase.h"

NS_ASSUME_NONNULL_BEGIN

@interface DnDBModifiers : DoJSONBase

#warning TODO

/*
 "modifiers": {
   "race": [
     {
       "id": "racialTrait_6_1339",
       "entityId": 2,
       "entityTypeId": 668550506,
       "type": "set-base",
       "subType": "darkvision",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Set Base",
       "friendlySubtypeName": "Darkvision",
       "isGranted": true,
       "bonusTypes": [],
       "value": 60,
       "componentId": 6,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_7_1340",
       "entityId": null,
       "entityTypeId": null,
       "type": "advantage",
       "subType": "saving-throws",
       "dice": null,
       "restriction": "Against Poison",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Advantage",
       "friendlySubtypeName": "Saving Throws",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 7,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_7_1341",
       "entityId": 10,
       "entityTypeId": 349597128,
       "type": "resistance",
       "subType": "poison",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Resistance",
       "friendlySubtypeName": "Poison",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 7,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_8_1342",
       "entityId": 19,
       "entityTypeId": 1782728300,
       "type": "proficiency",
       "subType": "battleaxe",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Battleaxe",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 8,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_8_1343",
       "entityId": 7,
       "entityTypeId": 1782728300,
       "type": "proficiency",
       "subType": "handaxe",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Handaxe",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 8,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_8_1344",
       "entityId": 10,
       "entityTypeId": 1782728300,
       "type": "proficiency",
       "subType": "light-hammer",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Light Hammer",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 8,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_8_1345",
       "entityId": 33,
       "entityTypeId": 1782728300,
       "type": "proficiency",
       "subType": "warhammer",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Warhammer",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 8,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_9_1464",
       "entityId": 103,
       "entityTypeId": 2103445194,
       "type": "proficiency",
       "subType": "brewers-supplies",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Brewer's Supplies",
       "isGranted": false,
       "bonusTypes": [],
       "value": null,
       "componentId": 9,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_68_1603",
       "entityId": 3,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "constitution-score",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Constitution Score",
       "isGranted": true,
       "bonusTypes": [],
       "value": 2,
       "componentId": 68,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_70_1605",
       "entityId": 1,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "strength-score",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Strength Score",
       "isGranted": true,
       "bonusTypes": [],
       "value": 2,
       "componentId": 70,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_71_1606",
       "entityId": 1,
       "entityTypeId": 174869515,
       "type": "proficiency",
       "subType": "light-armor",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Light Armor",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 71,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_71_1607",
       "entityId": 2,
       "entityTypeId": 174869515,
       "type": "proficiency",
       "subType": "medium-armor",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Medium Armor",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 71,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_84_1623",
       "entityId": 1,
       "entityTypeId": 906033267,
       "type": "language",
       "subType": "common",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Language",
       "friendlySubtypeName": "Common",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 84,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_84_1624",
       "entityId": 2,
       "entityTypeId": 906033267,
       "type": "language",
       "subType": "dwarvish",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Language",
       "friendlySubtypeName": "Dwarvish",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 84,
       "componentTypeId": 1960452172
     },
     {
       "id": "racialTrait_117_14723466",
       "entityId": null,
       "entityTypeId": null,
       "type": "ignore",
       "subType": "heavy-armor-speed-reduction",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Ignore",
       "friendlySubtypeName": "Heavy Armor Speed Reduction",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 117,
       "componentTypeId": 1960452172
     }
   ],
   "class": [
     {
       "id": "classFeature_62_1386",
       "entityId": null,
       "entityTypeId": null,
       "type": "bonus",
       "subType": "speed",
       "dice": null,
       "restriction": "while you aren’t wearing heavy armor",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Speed",
       "isGranted": true,
       "bonusTypes": [],
       "value": 10,
       "componentId": 62,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_61_1387",
       "entityId": null,
       "entityTypeId": null,
       "type": "set",
       "subType": "extra-attacks",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Set",
       "friendlySubtypeName": "Extra Attacks",
       "isGranted": true,
       "bonusTypes": [],
       "value": 1,
       "componentId": 61,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1474",
       "entityId": 1,
       "entityTypeId": 174869515,
       "type": "proficiency",
       "subType": "light-armor",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Light Armor",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1475",
       "entityId": 2,
       "entityTypeId": 174869515,
       "type": "proficiency",
       "subType": "medium-armor",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Medium Armor",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1476",
       "entityId": 4,
       "entityTypeId": 174869515,
       "type": "proficiency",
       "subType": "shields",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Shields",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1477",
       "entityId": 1,
       "entityTypeId": 660121713,
       "type": "proficiency",
       "subType": "simple-weapons",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Simple Weapons",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1478",
       "entityId": 2,
       "entityTypeId": 660121713,
       "type": "proficiency",
       "subType": "martial-weapons",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Martial Weapons",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1479",
       "entityId": null,
       "entityTypeId": null,
       "type": "proficiency",
       "subType": "strength-saving-throws",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Strength Saving Throws",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1480",
       "entityId": null,
       "entityTypeId": null,
       "type": "proficiency",
       "subType": "constitution-saving-throws",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Constitution Saving Throws",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1481",
       "entityId": 2,
       "entityTypeId": 1958004211,
       "type": "proficiency",
       "subType": "athletics",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Athletics",
       "isGranted": false,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_459_1482",
       "entityId": 17,
       "entityTypeId": 1958004211,
       "type": "proficiency",
       "subType": "intimidation",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Intimidation",
       "isGranted": false,
       "bonusTypes": [],
       "value": null,
       "componentId": 459,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_56_1665",
       "entityId": 3,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "constitution-score",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Constitution Score",
       "isGranted": false,
       "bonusTypes": [],
       "value": 1,
       "componentId": 56,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_57_1667",
       "entityId": 1,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "strength-score",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Strength Score",
       "isGranted": false,
       "bonusTypes": [],
       "value": 1,
       "componentId": 57,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_58_1669",
       "entityId": 3,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "constitution-score",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Constitution Score",
       "isGranted": false,
       "bonusTypes": [],
       "value": 1,
       "componentId": 58,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_59_1671",
       "entityId": 1,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "strength-score",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Strength Score",
       "isGranted": false,
       "bonusTypes": [],
       "value": 1,
       "componentId": 59,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_56_1789",
       "entityId": 3,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "constitution-score",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Constitution Score",
       "isGranted": false,
       "bonusTypes": [],
       "value": 1,
       "componentId": 56,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_57_1790",
       "entityId": 3,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "constitution-score",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Constitution Score",
       "isGranted": false,
       "bonusTypes": [],
       "value": 1,
       "componentId": 57,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_58_1791",
       "entityId": 3,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "constitution-score",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Constitution Score",
       "isGranted": false,
       "bonusTypes": [],
       "value": 1,
       "componentId": 58,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_59_1792",
       "entityId": 1,
       "entityTypeId": 1472902489,
       "type": "bonus",
       "subType": "strength-score",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Strength Score",
       "isGranted": false,
       "bonusTypes": [],
       "value": 1,
       "componentId": 59,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_55_2025",
       "entityId": null,
       "entityTypeId": null,
       "type": "set",
       "subType": "subclass",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Set",
       "friendlySubtypeName": "Subclass",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 55,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_52_2206",
       "entityId": null,
       "entityTypeId": null,
       "type": "set",
       "subType": "unarmored-armor-class",
       "dice": null,
       "restriction": "",
       "statId": 3,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Set",
       "friendlySubtypeName": "Unarmored Armor Class",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 52,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_54_5287",
       "entityId": null,
       "entityTypeId": null,
       "type": "advantage",
       "subType": "dexterity-saving-throws",
       "dice": null,
       "restriction": "against effects that you can see while not blinded, deafened, or incapacitated",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Advantage",
       "friendlySubtypeName": "Dexterity Saving Throws",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 54,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_63_1839586",
       "entityId": null,
       "entityTypeId": null,
       "type": "advantage",
       "subType": "initiative",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Advantage",
       "friendlySubtypeName": "Initiative",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 63,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_67_2050217",
       "entityId": null,
       "entityTypeId": null,
       "type": "protection",
       "subType": "0-hp",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Protection",
       "friendlySubtypeName": "0 HP",
       "isGranted": true,
       "bonusTypes": [],
       "value": 1,
       "componentId": 67,
       "componentTypeId": 12168134
     },
     {
       "id": "classFeature_53_3250140",
       "entityId": null,
       "entityTypeId": null,
       "type": "advantage",
       "subType": "strength-attacks",
       "dice": null,
       "restriction": "while attacking recklessly",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Advantage",
       "friendlySubtypeName": "Strength Attacks",
       "isGranted": true,
       "bonusTypes": [],
       "value": null,
       "componentId": 53,
       "componentTypeId": 12168134
     }
   ],
   "background": [
     {
       "id": "character_15119231_8482358",
       "entityId": 14,
       "entityTypeId": 1958004211,
       "type": "proficiency",
       "subType": "perception",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Perception",
       "isGranted": false,
       "bonusTypes": [],
       "value": null,
       "componentId": 15119231,
       "componentTypeId": 1581111423
     },
     {
       "id": "character_15119231_8482359",
       "entityId": 9,
       "entityTypeId": 1958004211,
       "type": "proficiency",
       "subType": "nature",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Nature",
       "isGranted": false,
       "bonusTypes": [],
       "value": null,
       "componentId": 15119231,
       "componentTypeId": 1581111423
     },
     {
       "id": "character_15119231_8482360",
       "entityId": 108,
       "entityTypeId": 2103445194,
       "type": "proficiency",
       "subType": "cooks-utensils",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Proficiency",
       "friendlySubtypeName": "Cook's Utensils",
       "isGranted": false,
       "bonusTypes": [],
       "value": null,
       "componentId": 15119231,
       "componentTypeId": 1581111423
     },
     {
       "id": "character_15119231_8482361",
       "entityId": 8,
       "entityTypeId": 906033267,
       "type": "language",
       "subType": "orc",
       "dice": null,
       "restriction": null,
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Language",
       "friendlySubtypeName": "Orc",
       "isGranted": false,
       "bonusTypes": [],
       "value": null,
       "componentId": 15119231,
       "componentTypeId": 1581111423
     }
   ],
   "item": [
     {
       "id": "gear_4726_465",
       "entityId": null,
       "entityTypeId": null,
       "type": "bonus",
       "subType": "armor-class",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": true,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Armor Class",
       "isGranted": true,
       "bonusTypes": [],
       "value": 1,
       "componentId": 4726,
       "componentTypeId": 112130694
     },
     {
       "id": "gear_4726_466",
       "entityId": null,
       "entityTypeId": null,
       "type": "bonus",
       "subType": "saving-throws",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": true,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Saving Throws",
       "isGranted": true,
       "bonusTypes": [],
       "value": 1,
       "componentId": 4726,
       "componentTypeId": 112130694
     },
     {
       "id": "weapon_5282_652",
       "entityId": null,
       "entityTypeId": null,
       "type": "bonus",
       "subType": "magic",
       "dice": null,
       "restriction": "",
       "statId": null,
       "requiresAttunement": false,
       "duration": null,
       "friendlyTypeName": "Bonus",
       "friendlySubtypeName": "Magic",
       "isGranted": true,
       "bonusTypes": [],
       "value": 2,
       "componentId": 5282,
       "componentTypeId": 112130694
     }
   ],
 },
 */

@property (nonatomic, retain) NSArray<NSString*>*       feat;
@property (nonatomic, retain) NSArray<NSString*>*       condition;

@end

NS_ASSUME_NONNULL_END
